// Generated by scripts/generate-assets.ts — do not edit by hand.
export type RuntimeAsset = {
  path: string;
  content: string;
};

export const runtimeAssets: RuntimeAsset[] = [
  { path: "skills/opx-code-review/SKILL.md", content: `---
name: opx-code-review
description: Review a change for correctness bugs and reuse/simplification opportunities, with file:line evidence for every finding. Use when reviewing a diff, plan, or implementation before it ships.
---

This skill produces an evidence-backed review, not vibes. Every finding cites a concrete location and explains the consequence.

## Scope the review

Review the actual change set — \`git diff\` (and \`git status\` for untracked files) against the merge base, or the files named in the task. Read enough surrounding code to judge correctness; a diff hunk in isolation lies.

## What to look for (in priority order)

1. **Correctness bugs** — logic errors, off-by-one, wrong conditionals, unhandled error/empty/null cases, race conditions, broken invariants, resource leaks, incorrect async/await.
2. **Contract & compatibility** — changed public APIs/types, breaking changes, missing migrations, inconsistent error handling.
3. **Security-adjacent** — unvalidated input, injection, secret handling, unsafe defaults. (For high-risk auth/billing/data work, defer to a dedicated security review.)
4. **Reuse & simplification** — duplicated logic that an existing helper covers, needless complexity, dead code introduced by the change.
5. **Tests** — behavior changed without a covering test; tests that assert implementation rather than behavior.

Avoid style nits the project's linter/formatter already handles. Skip speculative "could be faster" without evidence.

## Output

Group findings by severity (blocking / should-fix / optional). Each finding: \`file:line\`, what's wrong, the consequence, and a concrete fix. If the change is clean, say so plainly with what you checked. When run inside a Cerebro task, fold the verdict into your result block (Beast's \`GAPS FOUND\` contract).
` },
  { path: "skills/opx-debug/SKILL.md", content: `---
name: opx-debug
description: Reproduce-first debugging — isolate a failure with a minimal repro, find the root cause with evidence, fix it, and prove the fix. Use when something is broken, flaky, or behaving unexpectedly.
---

This skill enforces disciplined debugging: never guess-and-patch. Find the actual cause, then fix it.

## Procedure

1. **Reproduce first.** Get a reliable, minimal reproduction before changing anything — exact steps, inputs, environment, and the precise error/stack trace. If it's flaky, run it enough times to characterize the failure rate. A bug you can't reproduce, you can't confirm fixed.
2. **Locate, don't guess.** Bisect the surface: add targeted instrumentation (logs/asserts at boundaries), use \`git bisect\` to find the introducing commit, and use code search (the \`semble\` MCP if available) or grep to trace the data/control flow. Form a hypothesis and test it before editing.
3. **Find the root cause, not the symptom.** Ask why the bad state arose, not just where it surfaced. Fix the cause; a symptom patch that leaves the cause is a regression waiting to happen.
4. **Fix minimally.** Make the smallest change that addresses the root cause. Avoid drive-by refactors in a debugging change.
5. **Prove it.** Add a regression test (via the \`opx-test\` skill) that fails before the fix and passes after. Re-run the original reproduction to confirm it's resolved, and remove any temporary instrumentation.

## Report

In your \`TASK_RESULT\`, state the reproduction, the root cause (with file:line evidence), the fix, and the regression test + command that proves it. Note any remaining risk or related issues under \`ISSUES\`.
` },
  { path: "skills/opx-frontend-design/SKILL.md", content: `---
name: opx-frontend-design
description: Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, or applications. Generates creative, polished code that avoids generic AI aesthetics.
---

This skill guides creation of distinctive, production-grade frontend interfaces that avoid generic "AI slop" aesthetics. Implement real working code with exceptional attention to aesthetic details and creative choices.

The user provides frontend requirements: a component, page, application, or interface to build. They may include context about the purpose, audience, or technical constraints.

## Design Thinking

Before coding, understand the context and commit to a BOLD aesthetic direction:
- **Purpose**: What problem does this interface solve? Who uses it?
- **Tone**: Pick an extreme: brutally minimal, maximalist chaos, retro-futuristic, organic/natural, luxury/refined, playful/toy-like, editorial/magazine, brutalist/raw, art deco/geometric, soft/pastel, industrial/utilitarian, etc. There are so many flavors to choose from. Use these for inspiration but design one that is true to the aesthetic direction.
- **Constraints**: Technical requirements (framework, performance, accessibility).
- **Differentiation**: What makes this UNFORGETTABLE? What's the one thing someone will remember?

**CRITICAL**: Choose a clear conceptual direction and execute it with precision. Bold maximalism and refined minimalism both work - the key is intentionality, not intensity.

Then implement working code (HTML/CSS/JS, React, Vue, etc.) that is:
- Production-grade and functional
- Visually striking and memorable
- Cohesive with a clear aesthetic point-of-view
- Meticulously refined in every detail

## Frontend Aesthetics Guidelines

Focus on:
- **Typography**: Choose fonts that are beautiful, unique, and interesting. Avoid generic fonts like Arial and Inter; opt instead for distinctive choices that elevate the frontend's aesthetics; unexpected, characterful font choices. Pair a distinctive display font with a refined body font.
- **Color & Theme**: Commit to a cohesive aesthetic. Use CSS variables for consistency. Dominant colors with sharp accents outperform timid, evenly-distributed palettes.
- **Motion**: Use animations for effects and micro-interactions. Prioritize CSS-only solutions for HTML. Use Motion library for React when available. Focus on high-impact moments: one well-orchestrated page load with staggered reveals (animation-delay) creates more delight than scattered micro-interactions. Use scroll-triggering and hover states that surprise.
- **Spatial Composition**: Unexpected layouts. Asymmetry. Overlap. Diagonal flow. Grid-breaking elements. Generous negative space OR controlled density.
- **Backgrounds & Visual Details**: Create atmosphere and depth rather than defaulting to solid colors. Add contextual effects and textures that match the overall aesthetic. Apply creative forms like gradient meshes, noise textures, geometric patterns, layered transparencies, dramatic shadows, decorative borders, custom cursors, and grain overlays.

NEVER use generic AI-generated aesthetics: overused fonts (Inter, Roboto, Arial, system fonts, or a default like Space Grotesk), cliched color schemes (especially purple gradients on white), predictable layouts, and cookie-cutter patterns that lack context-specific character. Make unexpected choices that feel genuinely designed for the context — no two designs should converge; vary themes, fonts, and aesthetics across generations.

**IMPORTANT**: Match implementation complexity to the aesthetic vision. Maximalist designs need elaborate code with extensive animations and effects. Minimalist or refined designs need restraint, precision, and careful attention to spacing, typography, and subtle details. Elegance comes from executing the vision well — don't hold back; commit fully to a distinctive vision.
` },
  { path: "skills/opx-git/SKILL.md", content: `---
name: opx-git
description: Disciplined Git workflows — atomic commits with repo-matched style, safe rebase/squash, and history archaeology (blame, pickaxe, bisect). Use when committing changes, cleaning up history, or investigating when/why/by-whom code changed.
---

This skill makes Git operations disciplined and reviewable. Use it whenever you commit, reshape history, or investigate the past. It never commits, pushes, or rewrites history on its own — it acts only on an explicit request, and history-rewriting or force-push is gated behind the user's approval.

## 1. Read the repo before you act

Gather context in parallel: \`git status\`, \`git diff\`, \`git diff --staged\`, and \`git log --oneline -30\`. Detect the merge base with \`git merge-base HEAD main\` (fall back to \`master\`).

**Match the existing commit style** — infer it from the last ~30 commits, do not impose one:
- *Semantic* (\`feat:\`, \`fix:\`, \`chore:\` …) only if the history clearly uses it.
- *Plain* natural-language subjects if that dominates.
- *Short* 1–3 word subjects if that is the norm.
- Mirror the repo's language and capitalization conventions.

## 2. Commit atomically

Default to **multiple small commits**, not one large one. A change that spans different directories, component types, or independent concerns should be split so each commit is individually revertible and reviewable.

- Rough floor: about \`ceil(files_changed / 3)\` commits for a multi-file change — but cohesion wins over arithmetic.
- Keep tests with the implementation they cover; never split a test from its code.
- Order dependency-first: utilities → models → services → API/UI → config.
- If a single commit must touch many files, say in one sentence why they are one cohesive change.
- Verify each staged set with \`git diff --staged --stat\` before committing.

Avoid: one giant commit across unrelated files; grouping by file type instead of by feature; vague messages ("update stuff", "related changes").

## 3. Reshape history safely

- **Never rewrite history that has been pushed or shared without explicit user approval**, and **never rebase \`main\`/\`master\`**.
- Interactive squash/reorder: \`git rebase -i <base>\`; apply fixups with \`GIT_SEQUENCE_EDITOR=: git rebase -i --autosquash\`.
- Create fixups with \`git commit --fixup <sha>\` so autosquash can fold them.
- Resolve conflicts by editing, \`git add\` the resolved files, then \`git rebase --continue\`.
- Force-push only with \`--force-with-lease\`, never a bare \`--force\`, and only after approval.

## 4. Investigate history (archaeology)

- *When was a string added/removed?* pickaxe: \`git log -S"<string>" --oneline\` (use \`-G"<regex>"\` to match diff patterns).
- *Who wrote this line and when?* \`git blame -L <start>,<end> <file>\`.
- *Which commit introduced a bug?* \`git bisect start\` / \`good\` / \`bad\` to binary-search.
- *Full history of a file across renames?* \`git log --follow -- <file>\`.

## Output

When run inside a Cerebro task, fold the result into your \`TASK_RESULT\` (commits created, history actions taken with their approval, or findings). Respect plan approval gates for any destructive or history-rewriting action.
` },
  { path: "skills/opx-personal-assistant/SKILL.md", content: `---
name: opx-personal-assistant
description: Personal-assistant interaction layer for Cerebro — how to narrate, report status, and confirm at gates while orchestrating. Use whenever orchestrating a non-trivial request.
---

This skill governs **how you keep the user informed** while you orchestrate. It does not define the orchestration process — that lives in Cerebro's own instructions. This is purely the voice and reporting layer that makes the whole thing feel like a competent personal assistant rather than a black box.

## The one rule

**If the user would ever have to ask "what's happening?", you've already failed.** Talk to them at every phase transition and whenever something notable happens — a decision, a finding, a risk, a hand-off, a verified result, a blocker.

## Voice

- Concise and human: one or two lines per update, not paragraphs and not raw tool output. Translate tool results into plain status — "Wolverine finished the API layer; \`bun test\` passed" beats pasting JSON.
- Light cinematic Cerebro tone is fine, but clarity beats theatrics. Never trade information for flavor.
- The four phases (Intent Gate, Codebase Assessment, Smart Delegation, Independent Verification) are your internal scaffolding, **not lines to read aloud.** Never announce them by number or name — no "Phase 2", no "entering the Codebase Assessment phase". Describe what you're actually doing: "Mapping the codebase now — stack, entry points, and how it's tested." The user feels a smooth handoff, not a state machine.
- Be honest about uncertainty: if something is ambiguous, risky, or you made an assumption, say so.
- End each phase with a one-line "where we are / what's next."

## What to report, by phase

- **Intent Gate:** restate what you understood and name what you will and won't touch, then confirm before starting (unless they invoked a direct command or it's a simple direct request). Triage first — recommend a path rather than asking open-endedly — and present it as a selectable choice (recommended option first), so the user accepts with one keystroke or overrides.
- **Codebase Assessment:** a short findings summary before any work — stack, the files/areas in scope, conventions you'll follow, the verify command, and risks. Flag anything that changes the plan.
- **Smart Delegation:** announce the delegation plan up front (how many tasks, which specialist each goes to, what runs in parallel). Then, as you drive the loop, narrate each step: "Dispatching Storm for the header styling… done, verifying… ✓ passed. Next: the nav."
- **Independent Verification:** report the audit verdict plainly — what passed, what the auditor flagged, and what you're doing about it. Only say "done/verified" with evidence behind it.
- **Session Continuity:** on resume, say exactly where you're picking up ("Resuming: 3/8 tasks already verified, continuing with the API tests").

## Confirm at gates, not constantly

Ask the user only where a real decision is theirs (workflow choice, autonomy level, a genuine blocker, a destructive/high-risk action). Otherwise keep moving and keep narrating — in autonomous mode you don't ask questions, but you still report continuously.

When you do ask, use the interactive **\`question\` tool** so the user picks from selectable options instead of reading a list and typing a number — lead with your recommended option and mark it *(recommended)*. Fall back to a numbered text prompt only if that tool isn't available.
` },
  { path: "skills/opx-playwright/SKILL.md", content: `---
name: opx-playwright
description: Browser automation and UI verification with Playwright — render/interaction checks, screenshots, responsive layouts, forms, and login flows. Use to prove a UI change works.
---

This skill drives a real browser to verify and automate UI work: rendering, interactions, responsive behavior, accessibility, login flows, and link health. Use it to *prove* a UI change works rather than asserting it does.

## CRITICAL: detect the server first

Before navigating, find the running app. Check common dev ports (\`3000\`, \`5173\`, \`8080\`, \`4321\`, \`1313\`, …) or start the project's dev server if none is up. Never assume a URL — confirm it responds, then parameterize it (don't hard-code) so the same script works across environments.

## Preferred path: Playwright MCP server

If Playwright MCP \`browser_*\` tools are available in the session, use them directly — they give structured page state and are the cleanest way to drive the browser inside OpenCode:

1. \`browser_navigate\` to the detected URL.
2. \`browser_snapshot\` to read the accessibility tree (prefer this over screenshots for assertions — it's structured and cheap).
3. Interact with \`browser_click\` / \`browser_type\` / \`browser_select_option\` using roles/labels from the snapshot.
4. \`browser_take_screenshot\` for visual evidence; \`browser_resize\` to check breakpoints; \`browser_console_messages\` to catch runtime errors.

## Fallback path: npx playwright

If the MCP tools are not present, write a throwaway script to \`/tmp\` (never into the project tree) and run it with \`npx playwright\`:

- Ensure the browser is installed once: \`npx playwright install chromium\`.
- Write \`/tmp/opx-pw-<task>.mjs\` using \`@playwright/test\`'s \`chromium\`, navigate, assert, and capture screenshots to \`/tmp\`.
- Run headless in CI; use \`headless: false\` only when a human is watching.
- Clean up \`/tmp\` scripts when done.

## What to verify

- **Rendering & states**: default, hover, focus, loading, error, empty, disabled.
- **Responsive**: each required breakpoint (mobile/tablet/desktop) via viewport resize.
- **Flows**: login, form submit/validation, navigation — assert the resulting state, not just that a click happened.
- **Accessibility**: focus order, roles/labels in the snapshot, color-contrast-affecting states, reduced-motion.
- **Health**: no console errors; internal links resolve (no 404s).

## Output

Report concrete evidence — screenshot paths, the snapshot/assertions that passed or failed, console errors. When run inside a Cerebro task, put this in the \`VERIFICATION\` section of your \`TASK_RESULT\`; never claim visual verification happened unless you actually drove the browser.
` },
  { path: "skills/opx-security-review/SKILL.md", content: `---
name: opx-security-review
description: Security review of a change — find exploitable vulnerabilities with concrete evidence and severity. Use for high-risk work (auth, sessions, billing, data access, file/network/secret handling, public APIs) or when explicitly asked for a security pass.
---

This skill is a focused, high-signal security review. Report real, exploitable issues with evidence — not a generic checklist dump.

## Scope

Review the change set (\`git diff\` against the merge base) plus the trust boundaries it touches. Prioritize code that handles untrusted input, authentication/authorization, secrets, money, or user data.

## Threats to hunt

- **Injection** — SQL/NoSQL, command, path traversal, template/SSTI, XSS; any place untrusted input reaches an interpreter, query, filesystem, or markup without proper escaping/parameterization.
- **AuthN/AuthZ** — missing or incorrect authorization checks, IDOR (object access without ownership checks), privilege escalation, auth bypass, session fixation, tokens that don't expire or aren't validated.
- **Secrets & crypto** — hardcoded credentials, secrets in logs/errors/config committed to the repo, weak/again-rolled crypto, predictable randomness for security-sensitive values.
- **Data exposure** — over-broad responses leaking fields, missing access scoping, sensitive data in logs.
- **Unsafe defaults & deserialization** — permissive CORS, disabled TLS verification, untrusted deserialization, SSRF via user-controlled URLs, open redirects.
- **Dependencies** — newly added packages with known-risky patterns or unpinned/untrusted sources.

## Discipline

- Every finding needs **evidence** (file:line + how it's reached) and a **severity** (critical / high / medium / low) tied to real exploitability — not theoretical.
- Give a concrete remediation for each. Distinguish "exploitable now" from "hardening".
- Do not weaken or bypass an existing control to "make it work". Flag, don't fix-around.

## Output

Findings grouped by severity with evidence + remediation; if clean, state what trust boundaries you checked. When run inside a Cerebro task, fold the verdict into your result block (Emma Frost's \`VERDICT: OKAY | REJECT\`), rejecting when an unmitigated critical/high issue exists.
` },
  { path: "skills/opx-test/SKILL.md", content: `---
name: opx-test
description: Write and run focused automated tests — unit and integration — that actually exercise the change. Use when implementing a feature or fix, or when a task's verification needs real test coverage rather than assertions of correctness.
---

This skill makes testing deliberate and evidence-producing. Tests you write become Cerebro's deterministic verification (run via \`cerebro_verify\`), so they must genuinely fail when the code is wrong.

## Find the project's test setup first

Detect the framework and runner before writing anything: look for \`vitest\`/\`jest\`/\`bun test\`/\`pytest\`/\`go test\`/\`cargo test\` config and existing test files. Match the project's conventions — file naming, directory layout, assertion style, fixtures. Do not introduce a new framework when one exists.

## Write tests that earn their keep

- **Test behavior, not implementation.** Assert observable outcomes (return values, state, emitted events, HTTP responses), not internal calls — so refactors don't break tests spuriously.
- **Cover the real cases:** the happy path, the boundaries, the error paths, and the specific bug being fixed (write the failing test first for a fix).
- **Keep tests isolated and deterministic:** no shared mutable state, no real network/clock/randomness unless controlled. Seed or fake them.
- **One reason to fail per test.** Prefer several small, named tests over one sprawling case.
- **Verify the test fails first.** A test that passes against broken code proves nothing — confirm red, then green.

## Run and report

Run the focused suite (or the whole suite when fast) and capture the exact command + result. Pair each test file with the implementation it covers. Report the commands run and pass/fail counts in the \`TESTS RUN\` and \`VERIFICATION\` sections of your \`TASK_RESULT\`. If you could not run tests (missing deps, no runner), say so explicitly rather than claiming verification.
` },
];
