// Generated by scripts/generate-assets.ts — do not edit by hand.
export type RuntimeAsset = {
  path: string;
  content: string;
};

export const runtimeAssets: RuntimeAsset[] = [
  { path: "skills/opx-frontend-design/SKILL.md", content: `---
name: opx-frontend-design
description: Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, or applications. Generates creative, polished code that avoids generic AI aesthetics.
---

This skill guides creation of distinctive, production-grade frontend interfaces that avoid generic "AI slop" aesthetics. Implement real working code with exceptional attention to aesthetic details and creative choices.

The user provides frontend requirements: a component, page, application, or interface to build. They may include context about the purpose, audience, or technical constraints.

## Design Thinking

Before coding, understand the context and commit to a BOLD aesthetic direction:
- **Purpose**: What problem does this interface solve? Who uses it?
- **Tone**: Pick an extreme: brutally minimal, maximalist chaos, retro-futuristic, organic/natural, luxury/refined, playful/toy-like, editorial/magazine, brutalist/raw, art deco/geometric, soft/pastel, industrial/utilitarian, etc. There are so many flavors to choose from. Use these for inspiration but design one that is true to the aesthetic direction.
- **Constraints**: Technical requirements (framework, performance, accessibility).
- **Differentiation**: What makes this UNFORGETTABLE? What's the one thing someone will remember?

**CRITICAL**: Choose a clear conceptual direction and execute it with precision. Bold maximalism and refined minimalism both work - the key is intentionality, not intensity.

Then implement working code (HTML/CSS/JS, React, Vue, etc.) that is:
- Production-grade and functional
- Visually striking and memorable
- Cohesive with a clear aesthetic point-of-view
- Meticulously refined in every detail

## Frontend Aesthetics Guidelines

Focus on:
- **Typography**: Choose fonts that are beautiful, unique, and interesting. Avoid generic fonts like Arial and Inter; opt instead for distinctive choices that elevate the frontend's aesthetics; unexpected, characterful font choices. Pair a distinctive display font with a refined body font.
- **Color & Theme**: Commit to a cohesive aesthetic. Use CSS variables for consistency. Dominant colors with sharp accents outperform timid, evenly-distributed palettes.
- **Motion**: Use animations for effects and micro-interactions. Prioritize CSS-only solutions for HTML. Use Motion library for React when available. Focus on high-impact moments: one well-orchestrated page load with staggered reveals (animation-delay) creates more delight than scattered micro-interactions. Use scroll-triggering and hover states that surprise.
- **Spatial Composition**: Unexpected layouts. Asymmetry. Overlap. Diagonal flow. Grid-breaking elements. Generous negative space OR controlled density.
- **Backgrounds & Visual Details**: Create atmosphere and depth rather than defaulting to solid colors. Add contextual effects and textures that match the overall aesthetic. Apply creative forms like gradient meshes, noise textures, geometric patterns, layered transparencies, dramatic shadows, decorative borders, custom cursors, and grain overlays.

NEVER use generic AI-generated aesthetics like overused font families (Inter, Roboto, Arial, system fonts), cliched color schemes (particularly purple gradients on white backgrounds), predictable layouts and component patterns, and cookie-cutter design that lacks context-specific character.

Interpret creatively and make unexpected choices that feel genuinely designed for the context. No design should be the same. Vary between light and dark themes, different fonts, different aesthetics. NEVER converge on common choices (Space Grotesk, for example) across generations.

**IMPORTANT**: Match implementation complexity to the aesthetic vision. Maximalist designs need elaborate code with extensive animations and effects. Minimalist or refined designs need restraint, precision, and careful attention to spacing, typography, and subtle details. Elegance comes from executing the vision well.

Remember: Claude is capable of extraordinary creative work. Don't hold back, show what can truly be created when thinking outside the box and committing fully to a distinctive vision.
` },
  { path: "skills/opx-git/SKILL.md", content: `---
name: opx-git
description: Disciplined Git workflows — atomic commits with repo-matched style, safe rebase/squash, and history archaeology (blame, pickaxe, bisect). Use when committing changes, cleaning up history, or investigating when/why/by-whom code changed.
---

This skill makes Git operations disciplined and reviewable. Use it whenever you commit, reshape history, or investigate the past. It never commits, pushes, or rewrites history on its own — it acts only on an explicit request, and history-rewriting or force-push is gated behind the user's approval.

## 1. Read the repo before you act

Gather context in parallel: \`git status\`, \`git diff\`, \`git diff --staged\`, and \`git log --oneline -30\`. Detect the merge base with \`git merge-base HEAD main\` (fall back to \`master\`).

**Match the existing commit style** — infer it from the last ~30 commits, do not impose one:
- *Semantic* (\`feat:\`, \`fix:\`, \`chore:\` …) only if the history clearly uses it.
- *Plain* natural-language subjects if that dominates.
- *Short* 1–3 word subjects if that is the norm.
- Mirror the repo's language and capitalization conventions.

## 2. Commit atomically

Default to **multiple small commits**, not one large one. A change that spans different directories, component types, or independent concerns should be split so each commit is individually revertible and reviewable.

- Rough floor: about \`ceil(files_changed / 3)\` commits for a multi-file change — but cohesion wins over arithmetic.
- Keep tests with the implementation they cover; never split a test from its code.
- Order dependency-first: utilities → models → services → API/UI → config.
- If a single commit must touch many files, say in one sentence why they are one cohesive change.
- Verify each staged set with \`git diff --staged --stat\` before committing.

Avoid: one giant commit across unrelated files; grouping by file type instead of by feature; vague messages ("update stuff", "related changes").

## 3. Reshape history safely

- **Never rewrite history that has been pushed or shared without explicit user approval**, and **never rebase \`main\`/\`master\`**.
- Interactive squash/reorder: \`git rebase -i <base>\`; apply fixups with \`GIT_SEQUENCE_EDITOR=: git rebase -i --autosquash\`.
- Create fixups with \`git commit --fixup <sha>\` so autosquash can fold them.
- Resolve conflicts by editing, \`git add\` the resolved files, then \`git rebase --continue\`.
- Force-push only with \`--force-with-lease\`, never a bare \`--force\`, and only after approval.

## 4. Investigate history (archaeology)

- *When was a string added/removed?* pickaxe: \`git log -S"<string>" --oneline\` (use \`-G"<regex>"\` to match diff patterns).
- *Who wrote this line and when?* \`git blame -L <start>,<end> <file>\`.
- *Which commit introduced a bug?* \`git bisect start\` / \`good\` / \`bad\` to binary-search.
- *Full history of a file across renames?* \`git log --follow -- <file>\`.

## Output

When run inside a Cerebro task, fold the result into your \`TASK_RESULT\` (commits created, history actions taken with their approval, or findings). Respect plan approval gates for any destructive or history-rewriting action.
` },
  { path: "skills/opx-playwright/SKILL.md", content: `---
name: opx-playwright
description: Browser automation and UI verification with Playwright — test pages, fill forms, take screenshots, check responsive layouts, validate UX, exercise login flows, and check links. Prefers the Playwright MCP server when available; otherwise runs npx playwright scripts.
---

This skill drives a real browser to verify and automate UI work: rendering, interactions, responsive behavior, accessibility, login flows, and link health. Use it to *prove* a UI change works rather than asserting it does.

## CRITICAL: detect the server first

Before navigating, find the running app. Check common dev ports (\`3000\`, \`5173\`, \`8080\`, \`4321\`, \`1313\`, …) or start the project's dev server if none is up. Never assume a URL — confirm it responds, then parameterize it (don't hard-code) so the same script works across environments.

## Preferred path: Playwright MCP server

If Playwright MCP browser tools are available in the session (e.g. \`browser_navigate\`, \`browser_snapshot\`, \`browser_click\`, \`browser_type\`, \`browser_take_screenshot\`, \`browser_resize\`, \`browser_console_messages\`), use them directly — they give structured page state and are the cleanest way to drive the browser inside OpenCode:

1. \`browser_navigate\` to the detected URL.
2. \`browser_snapshot\` to read the accessibility tree (prefer this over screenshots for assertions — it's structured and cheap).
3. Interact with \`browser_click\` / \`browser_type\` / \`browser_select_option\` using roles/labels from the snapshot.
4. \`browser_take_screenshot\` for visual evidence; \`browser_resize\` to check breakpoints; \`browser_console_messages\` to catch runtime errors.

## Fallback path: npx playwright

If the MCP tools are not present, write a throwaway script to \`/tmp\` (never into the project tree) and run it with \`npx playwright\`:

- Ensure the browser is installed once: \`npx playwright install chromium\`.
- Write \`/tmp/opx-pw-<task>.mjs\` using \`@playwright/test\`'s \`chromium\`, navigate, assert, and capture screenshots to \`/tmp\`.
- Run headless in CI; use \`headless: false\` only when a human is watching.
- Clean up \`/tmp\` scripts when done.

## What to verify

- **Rendering & states**: default, hover, focus, loading, error, empty, disabled.
- **Responsive**: each required breakpoint (mobile/tablet/desktop) via viewport resize.
- **Flows**: login, form submit/validation, navigation — assert the resulting state, not just that a click happened.
- **Accessibility**: focus order, roles/labels in the snapshot, color-contrast-affecting states, reduced-motion.
- **Health**: no console errors; internal links resolve (no 404s).

## Output

Report concrete evidence — screenshot paths, the snapshot/assertions that passed or failed, console errors. When run inside a Cerebro task, put this in the \`VERIFICATION\` section of your \`TASK_RESULT\`; never claim visual verification happened unless you actually drove the browser.
` },
];
