/**
 * Generate src/runtime/generated-assets.ts from source assets.
 *
 * Open X-Men is plugin-only: agents and commands register through the plugin at load
 * (from the TypeScript factories/definitions), and no .opencode/ or .cerebro/ files are
 * written into projects. The only assets shipped at runtime are skills, which `open-xmen
 * install` writes into the global OpenCode config dir.
 *
 * Source:
 *   - src/assets/skills/  — OpenCode skills (skills/<name>/SKILL.md)
 *
 * Run with: bun scripts/generate-assets.ts
 */

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const outputPath = path.join(repoRoot, "src/runtime/generated-assets.ts");
const skillsAssetsDir = path.join(repoRoot, "src/assets/skills");

type Asset = { path: string; content: string };

// Walk a source tree into a destination prefix.
function walkAssets(rootDir: string, destPrefix: string): Asset[] {
  if (!existsSync(rootDir)) return [];
  const assets: Asset[] = [];
  function walk(dir: string) {
    for (const entry of readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else {
        const relPath = path.relative(rootDir, full).replace(/\\/g, "/");
        assets.push({ path: `${destPrefix}/${relPath}`, content: readFileSync(full, "utf8") });
      }
    }
  }
  walk(rootDir);
  return assets;
}

function escapeContent(content: string): string {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main() {
  // Skills install to the global OpenCode config dir (<configDir>/skills/<name>/SKILL.md).
  const assets: Asset[] = walkAssets(skillsAssetsDir, "skills");

  // Stable sort by path
  assets.sort((a, b) => a.path.localeCompare(b.path));

  const entries = assets
    .map(({ path: p, content }) => `  { path: ${JSON.stringify(p)}, content: \`${escapeContent(content)}\` }`)
    .join(",\n");

  const output = `// Generated by scripts/generate-assets.ts — do not edit by hand.
export type RuntimeAsset = {
  path: string;
  content: string;
};

export const runtimeAssets: RuntimeAsset[] = [
${entries},
];
`;

  writeFileSync(outputPath, output, "utf8");
  console.log(`Wrote ${assets.length} assets to ${path.relative(repoRoot, outputPath)}`);
}

main();
