/**
 * Generate src/runtime/generated-assets.ts from source assets.
 *
 * Sources:
 *   - src/assets/cerebro/  — Cerebro runtime content (.cerebro/ files); real files, real extensions
 *   - src/agents/          — OpenCode agent markdown (via factories)
 *   - src/commands/        — OpenCode command markdown (via definitions)
 *   - AGENTS.md            — Repository-level operating instructions
 *
 * Run with: bun scripts/generate-assets.ts
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { toOpenCodeMarkdown } from "../src/agents/markdown.ts";
import {
  createBeastAgent,
  createCerebroAgent,
  createCyclopsAgent,
  createCypherAgent,
  createEmmaFrostAgent,
  createForgeAgent,
  createJeanGreyAgent,
  createLegionAgent,
  createNightcrawlerAgent,
  createProfessorXAgent,
  createSageAgent,
  createStormAgent,
  createWolverineAgent,
} from "../src/agents/index.ts";
import { CEREBRO_COMMAND_DEFINITIONS, toOpenCodeCommandMarkdown } from "../src/commands/definitions.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const outputPath = path.join(repoRoot, "src/runtime/generated-assets.ts");
const cerebroAssetsDir = path.join(repoRoot, "src/assets/cerebro");

type Asset = { path: string; content: string };

// ─── Walk src/assets/cerebro/ ────────────────────────────────────────────────

function walkCerebroAssets(): Asset[] {
  const assets: Asset[] = [];
  function walk(dir: string) {
    for (const entry of readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else {
        const relPath = path.relative(cerebroAssetsDir, full).replace(/\\/g, "/");
        assets.push({ path: `.cerebro/${relPath}`, content: readFileSync(full, "utf8") });
      }
    }
  }
  walk(cerebroAssetsDir);
  return assets;
}

// ─── Agent markdown from factories ───────────────────────────────────────────

const agentFactories = [
  createCerebroAgent,
  createLegionAgent,
  createCypherAgent,
  createProfessorXAgent,
  createWolverineAgent,
  createJeanGreyAgent,
  createStormAgent,
  createCyclopsAgent,
  createForgeAgent,
  createNightcrawlerAgent,
  createSageAgent,
  createBeastAgent,
  createEmmaFrostAgent,
];

function buildAgentAssets(): Asset[] {
  return agentFactories.map((factory) => {
    const definition = factory();
    return {
      path: `.opencode/agents/${definition.name}.md`,
      content: toOpenCodeMarkdown(definition),
    };
  });
}

// ─── Command markdown from definitions ───────────────────────────────────────

function buildCommandAssets(): Asset[] {
  return CEREBRO_COMMAND_DEFINITIONS.map((cmd) => ({
    path: `.opencode/commands/${cmd.name}.md`,
    content: toOpenCodeCommandMarkdown(cmd),
  }));
}

// ─── Assemble and write ───────────────────────────────────────────────────────

function escapeContent(content: string): string {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main() {
  const assets: Asset[] = [
    // .cerebro/ runtime content — from real files in src/assets/cerebro/
    ...walkCerebroAssets(),

    // .opencode/ files — from TypeScript factories and definitions
    { path: ".opencode/.gitignore", content: "node_modules\npackage.json\npackage-lock.json\nbun.lock\n.gitignore" },
    ...buildAgentAssets(),
    ...buildCommandAssets(),

    // Repository-level instructions
    { path: "AGENTS.md", content: readFileSync(path.join(repoRoot, "AGENTS.md"), "utf8") },
  ];

  // Stable sort by path
  assets.sort((a, b) => a.path.localeCompare(b.path));

  const entries = assets
    .map(({ path: p, content }) => `  { path: ${JSON.stringify(p)}, content: \`${escapeContent(content)}\` }`)
    .join(",\n");

  const output = `// Generated by scripts/generate-assets.ts — do not edit by hand.
export type RuntimeAsset = {
  path: string;
  content: string;
};

export const runtimeAssets: RuntimeAsset[] = [
${entries},
];
`;

  writeFileSync(outputPath, output, "utf8");
  console.log(`Wrote ${assets.length} assets to ${path.relative(repoRoot, outputPath)}`);
}

main();
